### ISSUE TITLE
Einfärben der Karte nach Infektionsgeschehen

### ISSUE THREAD

**Issue by KayKoehle** [sayffaerth/InfoVis_Group3_Project#1]
Die Deutschlandkarte soll Eingefärbt werden nach den Fallzahlen 
Mögliche Datenquelle: https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/ef4b445a53c1406892257fe63129a8ea_0/data

Beispielimplementationen 
https://www.d3-graph-gallery.com/graph/choropleth_basic.html
https://observablehq.com/@d3/choropleth

**Comment by alxschmidt** [comment]
Done zu folgendem Grad:
Die Deutschlandkarte holt sich die tagesaktuellen Zahlen von der oben angegebenen Seite ( https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/ef4b445a53c1406892257fe63129a8ea_0/data ) und färbt die Bundesländer anhand ihrem Inzidenzwert ein (skaliert zwischen 0 und 200).
